[package]
name = "phase1-coordinator"
version = "0.3.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Coordinator implementation of Phase 1"
homepage = "https://github.com/AleoHQ/aleo-setup"
repository = "https://github.com/AleoHQ/aleo-setup"
license = "MIT/Apache-2.0"
edition = "2018"

[[bin]]
name = "phase1-coordinator"
path = "src/main.rs"

[dependencies]
phase1 = { path = "../phase1" }
phase1-cli = { path = "../phase1-cli" }
setup-utils = { path = "../setup-utils", default-features = false }

zexe_algebra = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra", version = "0.1.0", features = ["bls12_377", "bw6_761", "derive"] }

anyhow = { version = "1.0.32" }
chrono = { version = "0.4", features = ["serde"] }
ctrlc = { version = "3.1.7" }
dotenv = { version = "0.15" }
evmap = { version = "10.0.2" }
function_name = { version = "0.2.0", optional = true }
itertools = { version = "0.9.0" }
lazy_static = { version = "1.4.0" }
memmap = { version = "0.7.0" }
once_cell = { version = "1.4.1", optional = true }
rand = { version = "0.7.3" }
rayon = { version = "1.4.1" }
secrecy = { version = "0.7.0" }
serde = { version = "1.0", features = ["derive"] }
serde-aux = { version = "0.6" }
serde-diff = { version = "0.3" }
serde_json = { version = "1.0" }
serial_test = { version = "0.5", optional = true }
tokio = { version = "0.2", features = ["full"] }
toml = { version = "0.5.6" }
tracing = { version = "0.1.19" }
tracing-subscriber = { version = "0.2" }
url = { version = "1.0" }
url_serde = { version = "0.2.0" }

[dev-dependencies]
function_name = { version = "0.2.0" }
lazy_static = { version = "1.4.0" }
once_cell = { version = "1.4.1" }
serial_test = { version = "0.5" }

[features]
default = ["once_cell"]
testing = ["function_name", "once_cell", "serial_test"]
silent = []
